// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UIr2VvXYWXQ8QKoZv0Y_llGUpv-GO0M',
    appId: '1:457151601245:web:1313d698f091c27d320bb4',
    messagingSenderId: '457151601245',
    projectId: 'el-moos-b9340',
    authDomain: 'el-moos-b9340.firebaseapp.com',
    storageBucket: 'el-moos-b9340.appspot.com',
    measurementId: 'G-TXQD326SY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgnTpqjBiy5r4bo5Qig6EBHxtlQm9TDU',
    appId: '1:457151601245:android:3c7dc132b08e9f02320bb4',
    messagingSenderId: '457151601245',
    projectId: 'el-moos-b9340',
    storageBucket: 'el-moos-b9340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFEXpFvALzS3ohT9kOhz1NtLm5IZwyrk',
    appId: '1:457151601245:ios:03dc0cd7028ee968320bb4',
    messagingSenderId: '457151601245',
    projectId: 'el-moos-b9340',
    storageBucket: 'el-moos-b9340.appspot.com',
    iosClientId: '457151601245-8g0jgv7ae320d6uabqc5f1bdclmsa7vg.apps.googleusercontent.com',
    iosBundleId: 'com.AHorus.ElMoos.elMoos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFEXpFvALzS3ohT9kOhz1NtLm5IZwyrk',
    appId: '1:457151601245:ios:03dc0cd7028ee968320bb4',
    messagingSenderId: '457151601245',
    projectId: 'el-moos-b9340',
    storageBucket: 'el-moos-b9340.appspot.com',
    iosClientId: '457151601245-8g0jgv7ae320d6uabqc5f1bdclmsa7vg.apps.googleusercontent.com',
    iosBundleId: 'com.AHorus.ElMoos.elMoos',
  );
}
